name: Call Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  workflow_call:
    secrets:
        GCP_PROJECT_ID:
          required: true
        GCP_REGION:
          required: true
        GCP_GITHUB_TOKEN:
          required: true

jobs:
  call-reusable-workflow:
    uses: remotedef/reusable-repo/.github/workflows/build-and-push-dockerv1.yml@main  # Reference the remote workflow
    with:
      docker_image_name: 'my-app'  # Docker image name
      docker_tag: 'latest'  # Docker image tag
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_GITHUB_TOKEN: ${{ secrets.GCP_GITHUB_TOKEN }}  # GitHub token for WIF
