# .github/workflows/call-build-and-push.yml
name: Call Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment for GCP credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}  # Pass secret as an environment variable
        uses: remotedef/reusable-repo/.github/workflows/build-and-push-docker.yml@main  # Reference the remote workflow
        with:
          docker_image_name: 'my-app'  # Docker image name
          docker_tag: 'latest'  # Docker image tag
          gcp_project_id: 'your-gcp-project-id'  # Your GCP Project ID
          gcp_region: 'us-central1'  # The region where your Artifact Registry is located
