name: Call Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch

jobs:
  call-reusable-workflow:
    uses: remotedef/reusable-repo/.github/workflows/build-and-push-docker.yml@main  # Reference the remote workflow
    with:
      docker_image_name: 'my-app'  # Docker image name
      docker_tag: 'v2'  # Docker image tag
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      #GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_GITHUB_TOKEN: ${{ secrets.GCP_GITHUB_TOKEN }}  # GitHub token for WIF
